---
language: ruby
sudo: false
addons:
  apt:
    packages:
      - libaugeas-dev
    sources:
      - augeas
cache: bundler
bundler_args: --without system_tests
script: ["bundle exec rake validate", "bundle exec rake lint", "bundle exec rake spec SPEC_OPTS='--format documentation'"]
matrix:
  fast_finish: true
  include:
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.4
    env: PUPPET_GEM_VERSION="~> 5.0"
  - rvm: 2.5
    env: PUPPET_GEM_VERSION="~> 6.0"
notifications:
  email: false
deploy:
  provider: puppetforge
  user: camptocamp
  password:
    secure: "ZgHcCFzPY4m0F8E4l0d6PHKdlFYcDPuYiPo8RBfPOQJP+FwcpGAbC/7wLt4qZXx6l7Aw55u9en3hVdoWlsmz+ttBoxecJiMBYf2V70U63C2CltR0iDqYULPPCAz9u6TQHq4GQ+bIR+BZOMkD+kghRP38oxj39WsBszqsb5AzfsM="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.4
